name: temp
on:
    workflow_dispatch:

jobs:
    temp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run
              run: echo "Hello World"